<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-17T08:52:53Z" name="Default suite" finished-at="2021-02-17T08:53:14Z" duration-ms="21485">
    <groups>
    </groups>
    <test started-at="2021-02-17T08:52:53Z" name="Default test" finished-at="2021-02-17T08:53:14Z" duration-ms="21485">
      <class name="Tests.HomePageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:52:53Z" name="setUp" finished-at="2021-02-17T08:52:58Z" duration-ms="5150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setupHomePage()[pri:0, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:52:58Z" name="setupHomePage" finished-at="2021-02-17T08:52:58Z" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupHomePage -->
        <test-method signature="verifyTitle()[pri:1, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:52:58Z" name="verifyTitle" finished-at="2021-02-17T08:53:02Z" duration-ms="4133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method signature="doPostTest()[pri:2, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:53:02Z" name="doPostTest" finished-at="2021-02-17T08:53:05Z" duration-ms="2329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doPostTest -->
        <test-method signature="verifyPostText()[pri:3, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:53:05Z" name="verifyPostText" finished-at="2021-02-17T08:53:05Z" duration-ms="58" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [new---1112] but found [new---1111]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [new---1112] but found [new---1111]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.HomePageTest.verifyPostText(HomePageTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPostText -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.HomePageTest@180da663]" started-at="2021-02-17T08:53:05Z" name="tearDown" finished-at="2021-02-17T08:53:14Z" duration-ms="9295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
